export const AUDIT_ACTIONS = {
  USER_STATUS_CHANGE: "USER_STATUS_CHANGE",
  CLASS_STATUS_CHANGE: "CLASS_STATUS_CHANGE",
  CERTIFICATION_APPROVED: "CERTIFICATION_APPROVED",
  CERTIFICATION_REJECTED: "CERTIFICATION_REJECTED",
  USER_APPROVED: "USER_APPROVED",
  USER_DECLINED: "USER_DECLINED",
} as const;

export const AUDIT_TARGET_TYPES = {
  USER: "USER",
  CLASS: "CLASS",
  CERTIFICATION: "CERTIFICATION",
} as const;
